### ISSUE TITLE
The program is not being assembled into an EXE file, an error occurred when build.bat | Программа не собирается в исполняемый файл, произошла ошибка при build.bat

### ISSUE THREAD

**Issue by potap1978** [amnezia-vpn/amneziawg-windows-client#39]
![Image](https://github.com/user-attachments/assets/6011f1c0-5867-4d9a-814b-4a1d59598a6e)

**Comment by potap1978** [comment]
> Проверьте, создан ли подкаталог «amd64» — там должен быть amneziawg.exe.
> 
> «Ошибка» исходит не от компилятора/линковщика, а от build.bat, пытающегося удалить/переместить некоторые остатки.

The amd64 directory was not created

**Comment by potap1978** [comment]
> Ooops, the build script says "Building program x86" (visible on your screenshot).... so check for "x86" subdir instead of "amd64".
> 
> (I had the same problem but figured it out).

Video with continuation x86

![Image](https://github.com/user-attachments/assets/2a4ba0e1-e69d-414f-80ac-816ab4c818c2)

**Comment by macruspareto** [comment]
Right ! Now open build.bat - scroll down to lines 43, 44, 45
There you can see x86, amd64, arm64.
Delete or comment out lines 43 and 45.
Leave only amd64 and try to build it again.

Should be working. I guess you gotta need wintun.dll (from .deps\wintun\bin\amd64).

**Comment by potap1978** [comment]
> Right ! Now open build.bat - scroll down to lines 43, 44, 45 There you can see x86, amd64, arm64. Delete or comment out lines 43 and 45. Leave only amd64 and try to build it again.
> 
> Should be working. I guess you gotta need wintun.dll (from .deps\wintun\bin\amd64).
------------------------
	call :build_plat x64 x86_64 amd64 || goto :error
:	call :build_plat x86 i686 386 || goto :error
:	call :build_plat arm64 aarch64 arm64 || goto :error
------------------------
It worked !
But the same errors still remained

**Comment by RomikB** [comment]
В скрипте ошибка добавил PR #42

**Comment by RomikB** [comment]
Починили, пожно закрывать.
